export { capitalizeResponse } from './Core/CoreAPI';
export { generateQueryString } from './Core/CoreAPI';
export { default as CoreAPI } from './Core/CoreAPI';
export { default as PoliciesAPI } from './Processes/PoliciesAPI';
export { default as DashboardAPI } from './Dashboard/DashboardAPI';
export { default as DocumentsAPI } from './Documents/DocumentsAPI';
export { default as IdentityServerAPI } from './IdentityServer/IdentityServerAPI';
export { default as FirebaseAuthAPI } from './FirebaseAuth/FirebaseAuthAPI';
export { default as LambdaAPI } from './Lambda/LambdaAPI';
export { default as NotificationsAPI } from './Notifications/NotificationsAPI';
export { default as NovoCotadorAPI } from './NovoCotador/NovoCotadorAPI';
export { default as PolicyHolderAPI } from './PolicyHolder/PolicyHolderAPI';
export { default as RepositoryAPI } from './Repository/RepositoryAPI';
export { default as PainelTomadorAPI } from './PainelTomador/PainelTomadorAPI';
export { default as BackOfficeAPI } from './BackOffice/BackOfficeAPI';
export { default as AccountStatementAPI } from './AccountStatement/AccountStatementAPI';
export { default as TermsAPI } from './Terms/TermsAPI';
export { default as AuthAPI } from './Authentication/AuthAPI';
